function M = ccmPlotGUI_openFig(M)
% Open the ccmPlot GUI figure.
%
% 2011 KVH: adapted from rmPlotGUI_openfig.

% switch for dealing with java figures
javaFigs = mrvJavaFeature;

% open the figure
figName = sprintf('ccmPlotGUI %s (%s)', M.roi.name, M.dataType);
M.fig = figure('Color', 'w', 'Name', figName, ...
			   'Units', 'pixels', 'Position', [100 100 1000 480]);		   

% create a set of axes for showing the time series / prediction / RSS
M.ui.tsAxes = subplot(2,4, [1, 2, 3, 5, 6, 7]); 

% create sliders / text controls
callback = 'ccmPlotGUI([],[],1);';
M.ui.model = uicontrol('Style', 'popupmenu', ...
    'Units', 'norm', 'Position', [.75 .83 .2 .1], ...
    'BackgroundColor', 'w', 'FontSize', 10, ...
    'Callback', callback, ...
    'String', 'CC-pRF model', 'Value', 1);

M.ui.showCheck = uicontrol('Style', 'checkbox', ...
    'Units', 'norm', 'Position', [.747 .30 .2 .06], ...
    'BackgroundColor', 'w', 'FontSize', 11, ...
    'Callback', callback, 'Min', 0, 'Max', 1, ...
    'String', 'Show on mesh', 'Value', 0);

M.ui.voxel = mrvSlider([.75 .70 .2 .06], 'Voxel', ...
    'Range', [1 size(M.tSeries, 2)], 'IntFlag', 1, 'Value', 1, ...
    'MaxLabelFlag', 1, 'FontSize', 10, ...
    'Color', 'w', 'Callback', callback);

callback = ['opt = get(gcbo, ''Value'') + 1;  tmp = {''off'' ''on''}; ' ...
    'set( get(gcbo, ''UserData''), ''Visible'', tmp{opt} ); ' ...
    'clear opt tmp; '];

M.ui.tsCheck = uicontrol('Style', 'checkbox', ...
    'Units', 'norm', 'Position', [.747 .60 .2 .06], ...
    'BackgroundColor', 'w', 'FontSize', 11, ...
    'Callback', callback, 'Min', 0, 'Max', 1, ...
    'String', 'Voxel Time Series', 'Value', 1);

M.ui.predCheck = uicontrol('Style', 'checkbox', ...
    'Units', 'norm', 'Position', [.747 .50 .2 .06], ...
    'BackgroundColor', 'w', 'FontSize', 11, ...
    'Callback', callback, 'Min', 0, 'Max', 1, ...
    'String', 'Prediction', 'Value', 1);

M.ui.resCheck = uicontrol('Style', 'checkbox', ...
    'Units', 'norm', 'Position', [.747 .40 .2 .06], ...
    'BackgroundColor', 'w', 'FontSize', 11, ...
    'Callback', callback, 'Min', 0, 'Max', 1, ...
    'String', 'Residuals', 'Value', 0);

% add text uicontrols which will contain outputs on the calculations
M.ui.coordsText = uicontrol('Style', 'text', ...
	'HorizontalAlignment', 'left', ...	
    'Units', 'norm', 'Position', [.75 .15 .2 .1], ...
    'BackgroundColor', 'w', 'FontSize', 9, ...
    'FontWeight', 'bold', 'String', '');

M.ui.r2Text = uicontrol('Style', 'text', ...
	'HorizontalAlignment', 'left', ...
    'Units', 'norm', 'Position', [.75 .1 .2 .1], ...
    'BackgroundColor', 'w', 'FontSize', 9, ...
    'FontWeight', 'bold', 'String', '');

M.ui.xyzText = uicontrol('Style', 'text', ...
	'HorizontalAlignment', 'left', ...
    'Units', 'norm', 'Position', [.75 .05 .2 .1], ...
    'BackgroundColor', 'w', 'FontSize', 9, ...
    'FontWeight', 'bold', 'String', '');

M.ui.sigmaText = uicontrol('Style', 'text', ...
	'HorizontalAlignment', 'left', ...
    'Units', 'norm', 'Position', [.75 0 .2 .1], ...
    'BackgroundColor', 'w', 'FontSize', 9, ...
    'FontWeight', 'bold', 'String', ''); % 'Interpreter', 'tex',

% lastly, initialize the GUI graphics by performing an update:
set(M.fig, 'UserData', M);
% ccmPlotGUI_update(vw);
mrvJavaFeature(javaFigs);
return
